MatchGame/Controllers/MatchController.cs
using MatchGame.Helpers;
using MatchGame.Models;
using MatchGame.Objects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace MatchGame.Controllers
{
	[Authorize]
	public class MatchController : Controller
	{
		public ActionResult Main()
		{          
            return View();
		}

		[HttpPost]
		public ActionResult StartGame()
        {
            CacheHelper.Clear();
            MatchData matchData = MatchData.GetRandomGame();
			MatchData.SetToSession(Session, matchData);
			return new MatchActionResult(matchData);
		}
		[HttpPost]
		public ActionResult LoadGame(Guid id)
        {
            CacheHelper.Clear();
            MatchData matchData = MatchForSave.LoadFromXml(HttpContext.User.Identity.Name, id);
			MatchData.SetToSession(Session, matchData);
			return new MatchActionResult(matchData);
		}
		[HttpPost]
		public ActionResult DoStep([System.Web.Http.FromBody] Field field1, [System.Web.Http.FromBody] Field field2)
		{
			MatchData matchData = MatchData.GetFromSession(Session);
            if (matchData == null)
            {
                matchData = MatchData.GetRandomGame();
                MatchData.SetToSession(Session, matchData);
            }
			matchData.Refresh(field1, field2);
			return new MatchActionResult(matchData);
		}
	}
}

MatchGame/Controllers/SavedGamesController.cs
using MatchGame.Models;
using MatchGame.Objects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MatchGame.Controllers
{
	[Authorize]
	public class SavedGamesController : Controller
	{
		[HttpGet]
		public ActionResult Main()
		{
			MatchData[] games = MatchForSave.LoadFromXml(HttpContext.User.Identity.Name);
			return View(games);
		}

		[HttpPost]
		public ActionResult Save()
		{
			MatchData matchData = MatchData.GetFromSession(Session);
			if (matchData != null)
			{
				MatchForSave.Save(HttpContext.User.Identity.Name, matchData);
			}
			MatchData[] games = MatchForSave.LoadFromXml(HttpContext.User.Identity.Name);
			return View("Main", games);
		}
	}
}

MatchGame/Views/Match/Main.cshtml
@{
    ViewBag.Title = MatchGame.Textes.PLAY_TOOLBAR_TEXT;
    string startId = "Start";
    string gameId = "GameField";
    string saveId = "Save";
    string savedGamesId = "savedGames";
    string json = MatchGame.Models.FieldInfo.GetAsJson(MatchGame.Models.FieldInfo.GetFields());
}
<div class="page">
    <h2>@MatchGame.Textes.PLAY_TOOLBAR_TEXT</h2>
    <input id="@startId" type="button" value="@MatchGame.Textes.START" />
    <input id="@saveId" style="display:none;" type="button" value="@MatchGame.Textes.SAVE" />
    <input type="button" value="@MatchGame.Textes.END_GAME" onclick="document.location.href='@Url.Action("end","winners")';" />
    <div id="@gameId"></div>
    <div id="@savedGamesId">
        @{ Html.RenderAction("Main", "SavedGames"); }
    </div>
</div>
@section scripts{
    <script>
        var settings = new MatchSettings();
        settings.StartId = "@startId";
        settings.GameFieldId = "@gameId";
        settings.SaveId = "@saveId";
        settings.SavedGamesId = "@savedGamesId";
        settings.FieldTypes = @Html.Raw(json);
        var ctrl = new Match(settings);
        ctrl.Init();
    </script>
}